# -*- coding: utf-8 -*-
"""ANN_implementation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19nJydvoJmctjXIBNe3o406S6j4-7NrpD
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.utils import to_categorical
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

(X_train, y_train), (X_test, y_test) = mnist.load_data()

print("Training data shape:", X_train.shape)
print("Testing data shape:", X_test.shape)

sns.countplot(x=y_train)
plt.title("Class Distribution in Training Data")
plt.show()

X_train = X_train / 255.0
X_test = X_test / 255.0

y_train_cat = to_categorical(y_train)
y_test_cat = to_categorical(y_test)

ann = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(128, activation='relu'),
    Dense(64, activation='relu'),
    Dense(10, activation='softmax')
])

ann.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
ann.fit(X_train, y_train_cat, epochs=5, batch_size=128, validation_split=0.1)

test_loss, test_acc = ann.evaluate(X_test, y_test_cat, verbose=0)
print("ANN Accuracy:", test_acc)

