# -*- coding: utf-8 -*-
"""CatDogClassifierNet

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gLcQEJRup-9kt3zWTFKC-UYUgPTRITi3
"""

!pip install opendatasets

import opendatasets as od

od.download("https://www.kaggle.com/datasets/karakaggle/kaggle-cat-vs-dog-dataset")

#1. Importing Libraries

import matplotlib.pyplot as plt
import tensorflow as tf
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

from tensorflow import keras
from keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation, Dropout, Flatten, Dense
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.utils import image_dataset_from_directory
from tensorflow.keras.preprocessing.image import ImageDataGenerator, load_img
from tensorflow.keras.preprocessing import image_dataset_from_directory

import os
import matplotlib.image as mpimg

#2. Importing Dataset

data_path="./kaggle-cat-vs-dog-dataset"

#3. Visualizating the Data


fig = plt.gcf()
fig.set_size_inches(16, 16)

cat_dir = os.path.join('/content/kaggle-cat-vs-dog-dataset/kagglecatsanddogs_3367a/PetImages/Cat')
dog_dir = os.path.join('/content/kaggle-cat-vs-dog-dataset/kagglecatsanddogs_3367a/PetImages/Dog')
cat_names = os.listdir(cat_dir)
dog_names = os.listdir(dog_dir)

pic_index = 210

cat_images = [os.path.join(cat_dir, fname)
              for fname in cat_names[pic_index-8:pic_index]]
dog_images = [os.path.join(dog_dir, fname)
              for fname in dog_names[pic_index-8:pic_index]]

for i, img_path in enumerate(cat_images + dog_images):
    sp = plt.subplot(4, 4, i+1)
    sp.axis('Off')

    img = mpimg.imread(img_path)
    plt.imshow(img)

plt.show()

import os
import tensorflow as tf

cat_dir = '/content/kaggle-cat-vs-dog-dataset/kagglecatsanddogs_3367a/PetImages/Cat'
dog_dir = '/content/kaggle-cat-vs-dog-dataset/kagglecatsanddogs_3367a/PetImages/Dog'

def clean_directory(directory_path):
    deleted_count = 0
    for filename in os.listdir(directory_path):
        file_path = os.path.join(directory_path, filename)

        if not os.path.isfile(file_path):
            continue

        try:
            img_bytes = tf.io.read_file(file_path)
            decoded_img = tf.io.decode_image(img_bytes)
            if decoded_img.shape[-1] not in [1, 3, 4]:
                raise ValueError("Invalid number of channels")

        except (tf.errors.InvalidArgumentError, ValueError, Exception) as e:
            print(f"Removing corrupted file: {file_path} - Error: {e}")
            os.remove(file_path)
            deleted_count += 1

    print(f"Cleaned {directory_path}: Removed {deleted_count} invalid files.")

clean_directory(cat_dir)
clean_directory(dog_dir)

#4. Splitting Dataset


base_dir='/content/kaggle-cat-vs-dog-dataset/kagglecatsanddogs_3367a/PetImages'

train_datagen = image_dataset_from_directory(base_dir,
                                                  image_size=(200,200),
                                                  subset='training',
                                                  seed = 1,
                                                 validation_split=0.1,
                                                  batch_size= 32)
test_datagen = image_dataset_from_directory(base_dir,
                                                  image_size=(200,200),
                                                  subset='validation',
                                                  seed = 1,
                                                 validation_split=0.1,
                                                  batch_size= 32)

#5. Model Architecture


model = tf.keras.models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(200, 200, 3)),
    layers.MaxPooling2D(2, 2),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D(2, 2),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D(2, 2),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D(2, 2),

    layers.Flatten(),
    layers.Dense(512, activation='relu'),
    layers.BatchNormalization(),
    layers.Dense(512, activation='relu'),
    layers.Dropout(0.1),
    layers.BatchNormalization(),
    layers.Dense(512, activation='relu'),
    layers.Dropout(0.2),
    layers.BatchNormalization(),
    layers.Dense(1, activation='sigmoid')
])

model.summary()

#7. Model Compilation and Training


model.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

history = model.fit (x=train_datagen,epochs=1,validation_data=test_datagen)

#8. Model Evaluation

history_df = pd.DataFrame(history.history)
history_df.loc[:, ['loss', 'val_loss']].plot()
history_df.loc[:, ['accuracy', 'val_accuracy']].plot()
plt.show()

from tensorflow.keras.preprocessing import image

def predict_image(image_path):
    img = image.load_img(image_path, target_size=(200, 200))
    plt.imshow(img)
    plt.show()
    img = image.img_to_array(img)
    img = np.expand_dims(img, axis=0)

    result = model.predict(img)
    print("Dog" if result >= 0.5 else "Cat")

predict_image('/content/kaggle-cat-vs-dog-dataset/kagglecatsanddogs_3367a/PetImages/Cat/0.jpg')
predict_image('/content/kaggle-cat-vs-dog-dataset/kagglecatsanddogs_3367a/PetImages/Dog/0.jpg')

