# -*- coding: utf-8 -*-
"""Clustering_implementation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16juxMAclS20HzLXaU_Ts8varh-TGrBMY
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans, AgglomerativeClustering
from scipy.cluster.hierarchy import dendrogram, linkage
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score, davies_bouldin_score
from scipy.cluster.hierarchy import dendrogram, linkage

from google.colab import files
file=files.upload()

data = pd.read_csv("/content/Mall_Customers.csv", header=0)
data.head()

data['Genre'] = data['Genre'].map({'Male': 0, 'Female': 1})
x=data.drop(['CustomerID'], axis=1)
x.head()

scaler = StandardScaler()
X_scaled = scaler.fit_transform(x)

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

kmeans = KMeans(n_clusters=5, random_state=42)
kmeans_labels = kmeans.fit_predict(X_scaled)

kmeans_silhouette = silhouette_score(X_scaled, kmeans_labels)
kmeans_db_index = davies_bouldin_score(X_scaled, kmeans_labels)

print("\nK-Means Clustering:")
print(f"Silhouette Score: {kmeans_silhouette:.3f}")
print(f"Davies–Bouldin Index: {kmeans_db_index:.3f}")

hier = AgglomerativeClustering(n_clusters=5, linkage='ward')
hier_labels = hier.fit_predict(X_scaled)


hier_silhouette = silhouette_score(X_scaled, hier_labels)
hier_db_index = davies_bouldin_score(X_scaled, hier_labels)

print("\nHierarchical Clustering:")
print(f"Silhouette Score: {hier_silhouette:.3f}")
print(f"Davies–Bouldin Index: {hier_db_index:.3f}")

plt.figure(figsize=(10, 5))
linkage_matrix = linkage(X_scaled, method='ward')
dendrogram(linkage_matrix)
plt.title("Hierarchical Clustering Dendrogram")
plt.xlabel("Customers")
plt.ylabel("Euclidean Distance")
plt.show()

