# -*- coding: utf-8 -*-
"""Decision tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UMQZz5jhRS7hkqWCmxLCBPqWbrXu7tp5
"""

# Decision tree
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

data = {
"Age": [22, 25, 47, 52, 46, 56, 28, 35, 40, 50],
"Income": [15000, 30000, 60000, 80000, 75000, 90000, 25000, 50000, 65000, 85000],
"Student": [1, 1, 0, 0, 0, 0, 1, 1, 0, 0],
"Purchased": [0, 0, 1, 1, 1, 1, 0, 1, 1, 1]

}

df = pd.DataFrame(data)

print(df)

df.shape

#select features and target
X = df[["Age", "Income", "Student"]]

y = df["Purchased"]

#Split Dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#Build Decision Tree
model = DecisionTreeClassifier(
criterion="gini",
max_depth=3,
random_state=42
)
model.fit(X_train, y_train)

model = DecisionTreeClassifier(
criterion="entropy",
max_depth=3,
random_state=42
)
model.fit(X_train, y_train)

#Prediction
y_pred = model.predict(X_test)

print("Predicted Values")

print(y_pred)

#actual values
print("Actual Values")

print(y_test.values)

#Accuracy
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

#Confusion matrix
cm = confusion_matrix(y_test, y_pred)

print(cm)

#classification report
print(classification_report(y_test, y_pred))

#feature importance
importance = model. feature_importances_

for feature, score in zip(X.columns, importance):
  print(feature, ":", round(score,3))

#visualize the decision tree
plt.figure(figsize=(14,8))

plot_tree(
model,
feature_names=X.columns,
class_names=["No Purchase", "Purchase"],
filled=True,
rounded=True,
fontsize=10
)
plt. show()

