# -*- coding: utf-8 -*-
"""Double_Ended_Queue_Array.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q7bmjiK3nLJ-37xBG1n8eqaJJJ7bX9Es
"""

class Deque:
    def __init__(self, size):
        self.size = size
        self.deque_arr = [None for _ in range(size)]
        self.left = -1
        self.right = -1

    def display_queue(self):
        front_pos = self.left
        rear_pos = self.right
        if self.left == -1:
            print("Queue is empty \n")
            return

        print("Queue elements:")
        if front_pos <= rear_pos:
            while front_pos <= rear_pos:
                print(self.deque_arr[front_pos])
                front_pos += 1
        else:
            while front_pos <= self.size - 1:
                print(self.deque_arr[front_pos])
                front_pos += 1
            front_pos = 0
            while front_pos <= rear_pos:
                print(self.deque_arr[front_pos])
                front_pos += 1
        print()

    def insert_left(self):
        if (self.left == 0 and self.right == self.size - 1) or (self.left == self.right + 1):
            print("Queue Overflow\n")
            return

        if self.left == -1:
            self.left = 0
            self.right = 0
        elif self.left == 0:
            self.left = self.size - 1
        else:
            self.left = self.left - 1

        val = int(input("Enter the element to add at left: "))
        self.deque_arr[self.left] = val

    def insert_right(self):
        if (self.left == 0 and self.right == self.size - 1) or (self.left == self.right + 1):
            print("Queue Overflow\n")
            return
        if self.left == -1:
            self.left = 0
            self.right = 0
        elif self.right == self.size - 1:
            self.right = 0
        else:
            self.right = self.right + 1

        val = int(input("Enter the element to add at right: "))
        self.deque_arr[self.right] = val

    def delete_left(self):
        if self.left == -1:
            print("Queue Underflow\n")
            return

        print("Element deleted from queue (left) is", self.deque_arr[self.left])

        if self.left == self.right:
            self.left = -1
            self.right = -1
        elif self.left == self.size - 1:
            self.left = 0
        else:
            self.left = self.left + 1

    def delete_right(self):
        if self.left == -1:
            print("Queue Underflow\n")
            return

        print("Element deleted from queue (right) is", self.deque_arr[self.right])

        if self.left == self.right:
            self.left = -1
            self.right = -1
        elif self.right == 0:
            self.right = self.size - 1
        else:
            self.right = self.right - 1



MAX = int(input("Enter the maximum size of the Deque: "))
q = Deque(MAX)

def enqueue_left_operation():
    print("ENQUEUE left")
    q.insert_left()

def enqueue_right_operation():
    print("ENQUEUE right")
    q.insert_right()

def dequeue_left_operation():
    print("DEQUEUE left")
    q.delete_left()

def dequeue_right_operation():
    print("DEQUEUE right")
    q.delete_right()

def display_operation():
    q.display_queue()

def exit_op():
    print("Exiting...")
    exit()

switcher = {
    0: enqueue_left_operation,
    1: enqueue_right_operation,
    2: dequeue_left_operation,
    3: dequeue_right_operation,
    4: display_operation,
    5: exit_op
}

def select(argument):
    func = switcher.get(argument, lambda: print("Invalid choice"))
    func()

print("\nMENU\n0: ENQUEUE left\n1: ENQUEUE right\n2: DEQUEUE left\n3: DEQUEUE right\n4: Display\n5: Exit")
while True:
    try:
        ch = int(input("Enter choice: "))
        select(ch)
        if ch == 5:
            break
    except ValueError:
        print("Please enter a valid integer choice.")

