# -*- coding: utf-8 -*-
"""GenAI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cHKOlM7ZKMMzrdd8yV-UtcbXPZdxoMJ-
"""

!nvidia-smi

!pip install langchain
!pip install langchain_community
!pip install langsmith
!pip install langchain_chroma
!pip install langchain_groq

!pip install unstructured

from langchain_community.document_loaders import UnstructuredFileIOLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_chroma import Chroma
from langchain_classic.chains import RetrievalQA
from langchain_groq import ChatGroq

import os
#groq
os.environ["GROQ_API_KEY"]="xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
#langchain
os. environ["LANGCHAIN_API_KEY"]="lxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
#environment
os. environ["LANGCHAIN_TRACKING_V2"]="true"
#project name
os. environ["LANGCHAIN_PROJECT"]="first"

print("enable tracking successfully !!! ")

import requests
url="https://codeunnati.edunetfoundation.com/faqs"

data=requests. get(url)

with open("codeunnati.pdf","wb") as f:
  f.write(data.content)

text_splitter=CharacterTextSplitter(chunk_size=1000, chunk_overlap=100)

from langchain_core import documents
with open("codeunnati.pdf","rb") as f:
  loader=UnstructuredFileIOLoader(f)
  documents=loader.load()
texts=text_splitter.split_documents(documents)

texts[2]

texts[0]

texts[3]

embedding=HuggingFaceEmbeddings()

presist_directory="vector_db"

chroma=Chroma. from_documents(documents=texts, embedding=embedding, persist_directory=presist_directory)

retriever=chroma.as_retriever()

llm=ChatGroq(model="llama-3.1-8b-instant",temperature=0)

qa_chain=RetrievalQA.from_chain_type(llm=llm,chain_type="stuff",retriever=retriever)

query="what is code unnati program"
response=qa_chain.invoke({"query":query})

print(response["result"])

import gradio as gr

def get_response(question):
  try:
    response=qa_chain.invoke({"query":question})
    return response["result"]
  except Exception as e:
    return str(e)


demo=gr.Interface(
    fn=get_response,
    inputs=gr.Text(
        lines=2,
        placeholder="Enter your query related to codeunnati program"

    ),
    outputs=gr.Text(
        lines=10,
        label="Response"

    ),
     title="Code unnatio Chat Bot",
     description="Ask the query related to the Codeunnati program"

    )
demo.launch(debug=True)



import requests
url="https://www.linkedin.com/jobs/"

data=requests. get(url)

with open("linkedin.pdf","wb") as f:
  f.write(data.content)

text_splitter=CharacterTextSplitter(chunk_size=1000, chunk_overlap=100)

from langchain_core import documents
with open("linkedin.pdf","rb") as f:
  loader=UnstructuredFileIOLoader(f)
  documents=loader.load()
texts=text_splitter.split_documents(documents)

texts[2]

texts[0]

embedding=HuggingFaceEmbeddings()

presist_directory="vector_db"

chroma=Chroma. from_documents(documents=texts, embedding=embedding, persist_directory=presist_directory)

retriever=chroma.as_retriever()

llm=ChatGroq(model="llama-3.1-8b-instant",temperature=0)

qa_chain=RetrievalQA.from_chain_type(llm=llm,chain_type="stuff",retriever=retriever)

query="what are linkedIn jobs"
response=qa_chain.invoke({"query":query})

print(response["result"])

import gradio as gr

def get_response(question):
  try:
    response=qa_chain.invoke({"query":question})
    return response["result"]
  except Exception as e:
    return str(e)


demo=gr.Interface(
    fn=get_response,
    inputs=gr.Text(
        lines=2,
        placeholder="Enter your query related to LinkedIn jobs"

    ),
    outputs=gr.Text(
        lines=10,
        label="Response"

    ),
     title="LinkedIn Chat Bot",
     description="Ask the query related to LinkedIn jobs"

    )
demo.launch(debug=True)

