# -*- coding: utf-8 -*-
"""rock_paper_scissors_game

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Zu_Crhq-smhza5xcW_G9vKaL4efNsDM
"""

from random import randint
t = [1,2,3]

computer = t[randint(0,2)]
player = False
print ("""1. Rock
2. Paper
3. Scissors""")
c=0
p=0
N=0
T=int(input("Enter the number of turns:"))
while N<T:
    player = int(input("Choose any number:"))
    if player == computer:
        print("Tie!")
    elif player == 1:
        if computer == 2:
            print("You lose! Paper covers Rock")
            c+=1
        else:
            print("You win! Rock smashes Scissors")
            p+=1
    elif player == 2:
        if computer == 3:
            print("You lose! Scissors cut Paper")
            c+=1
        else:
            print("You win! Paper covers Rock")
            p+=1
    elif player == 3:
        if computer == 1:
            print("You lose! Rock smashes Scissors")
            c+=1
        else:
            print("You win! Scissors cut Paper")
            p+=1
    else:
        print("That's not a valid play. Check your spelling!")

    computer = t[randint(0,2)]
    N+=1
if c>p:
    print ("You lose..... Computer wins with ",c," points")
elif p>c:
    print ("You win..! With ",p," points")
else:
    print ("The game is tie")