# -*- coding: utf-8 -*-
"""singly_linked_list_reversal

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14-hdN6ZhxGoXwssBPJRE6ppszJSk_pfo
"""

# program to create a linked list and display the node elements in reverse order

class Node:
  def __init__(self,data):
    self.item=data
    self.ref=None

class LinkedList:
  def __init__(self):
    self.start_node=None

  def insert_at_end(self,data):
    new_node=Node(data)
    if self.start_node is None:
      self.start_node=new_node
      return
    n=self.start_node
    while n.ref is not None:
      n=n.ref
    n.ref=new_node

  def traverse_list(self):
    if self.start_node is None:
      print("List has no elements")
      return
    else:
      n=self.start_node
      while n is not None:
        print(n.item,end="->")
        n=n.ref

  def reverse_LinkedList(self):
    prev=None
    n=self.start_node
    while n is not None:
      next=n.ref
      n.ref=prev
      prev=n
      n=next
    self.start_node=prev

new_li=LinkedList()
nums=int(input("How many nodes do you want to create:"))
for i in range(nums):
  value=int(input("Enter the value for the node:"))
  new_li.insert_at_end(value)
print("\n")
print("INSERT AT END")

new_li.traverse_list()
print("\n")
print("REVERSE ORDER")
new_li.reverse_LinkedList()
new_li.traverse_list()