# -*- coding: utf-8 -*-
"""TL_image identification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WceVFrl3QYEjWFv87pyVcNfy2d9iXzhQ

# ResNet50 used to classify ImageNet classes

ResNet-50 is a convolutional neural network that is 50 layers deep. We can load a pretrained version of the network trained on more than a million images from the ImageNet database. The pretrained network can classify images into 1000 object categories, such as keyboard, mouse, pencil, and many animals. As a result, the network has learned rich feature representations for a wide range of images. The network has an image input size of 224-by-224.

ImageNet is an extensive collection of images that have been used to train models, including ResNet50. There are over 1 million images and 1000 classes in this dataset.

img_to_array is used to convert a PIL image into a numpy array.
expand_dims expands the array by inserting a new axis at the specified position. Two parameters are required by this function.
"""

from tensorflow.keras.applications.resnet50 import ResNet50
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.resnet50 import preprocess_input, decode_predictions
import numpy as np
model = ResNet50(weights='imagenet')
img_path = 'elephant.jpg'
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)
preds = model.predict(x)

print('Predicted:', decode_predictions(preds, top=3)[0])

