# -*- coding: utf-8 -*-
"""Twitter_Sentiment_Analysis_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-trj_TXg_-m_5UGXQcY3Dymwb61DqvCs
"""

# Commented out IPython magic to ensure Python compatibility.
# Libraries for data preparation & visualisation

import re
import numpy as np
import pandas as pd
import seaborn as sns
sns.set(color_codes=True)
import matplotlib.pyplot as plt
# %matplotlib inline
from wordcloud import WordCloud


# Library to ignore warnings

import warnings
warnings.filterwarnings("ignore")

# Library for assigning sentiment label

from textblob import TextBlob

# Libraries for text analytics

import nltk
from nltk.stem.wordnet import WordNetLemmatizer
from nltk.stem.porter  import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer

# Libraries for ML modeling

from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold, ParameterGrid
from sklearn.model_selection import GridSearchCV, cross_val_score
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from imblearn.over_sampling import RandomOverSampler
from imblearn.pipeline import Pipeline
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import f1_score, classification_report

# Reading in data

##data = pd.read_csv('tweets.csv')
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

data = pd.read_csv('/content/drive/MyDrive/tweets.csv')  # update path if inside folder
data.head()

from google.colab import drive
drive.mount('/content/drive')

# Shape of data

data.shape

"""- There are 1951 rows & 4 columns"""

data.info()

"""- 'id' is a 16 digit random number associated with each tweet. This should have no relevance on final modeling & can be dropped
- 'created_at' is of object type & will be converted to datetime format
- 'location' has 442 missing records
"""

# Dropping 'id'

data = data.drop('id', axis=1)

# Changing datatype for created_at

data['created_at'] = pd.to_datetime(data['created_at'])

# Replacing missing records under location with 'unknown'

data = data.fillna('Unknown')

data.describe(include='all').T

"""- 'text' value is repeated in the dataset, e.g., text 'RT @NHLBlackhawks: Staying warm never looked s...' occurs 25 times in the dataset. This indicates some of the texts have retweets"""

# Checking duplicates

data.duplicated().sum()

"""- There are no duplicate records"""

# Checking for missing values

data.isnull().sum().sum()

"""- No further missing values

#### Feature Engineering & EDA
"""

# Language detection

!pip install langdetect

from langdetect import detect

def language_detection(text):

    try:
        language = detect(text)
        return(language)
    except:
        return('error')

data['language'] = data['text'].apply(language_detection)

data.head()

# Language

data['language'].value_counts()

# Filter the dataset to only contain english texts

data = data[data['language']=='en']
data.drop('language', axis=1, inplace=True)

# Shape of data

data.shape

"""- There are 1809 rows remaining"""

# Create new features from 'created_at'

# Day of the week
data['day_of_week'] = data['created_at'].dt.dayofweek
data['day_of_week'] = data['day_of_week'].replace({0:'Monday', 1:'Tuesday', 2:'Wednesday', 3:'Thursday',\
                                                   4:'Friday', 5:'Saturday',6:'Sunday'})

# Hour

data['hour']        = data['created_at'].dt.hour + data['created_at'].dt.minute/60

# Value counts for day_of_week

data['day_of_week'].value_counts()

"""- Majority of the tweets are on Wednesday (middle of the week), followed by Monday
- Least number of tweets are on Saturday or Sunday
"""

# Dropping the 'created_at' attribute

data = data.drop('created_at', axis=1)

# Let's create target column, i.e., sentiment associated with text

# Defining a function to assign sentiments (positive, negative or neutral)

def get_sentiment(text):
    blob = TextBlob(text)
    sentiment = blob.sentiment.polarity
    if sentiment > 0:
        return 'positive'
    elif sentiment < 0:
        return 'negative'
    else:
        return 'neutral'

data['sentiment'] = data['text'].apply(get_sentiment)

# Value counts for sentiment

data['sentiment'].value_counts()

"""- Maximum tweets have a positive sentiment followed by neutral sentiment"""

# function to create labeled barplots


def labeled_barplot(data, feature, target ,perc=False, n=None):

    total = len(data[feature])  # length of the column
    count = data[feature].nunique()
    if n is None:
        plt.figure(figsize=(count + 2, 5))
    else:
        plt.figure(figsize=(n + 2, 5))

    plt.xticks(rotation=90, fontsize=15)
    ax = sns.countplot(data=data.sort_values(by=target),x=feature,palette="Paired",hue=target,\
                       order=data[feature].value_counts().index[:n].sort_values(),)

    for p in ax.patches:
        if perc == True:
            label = "{:.1f}%".format(100 * p.get_height() / total)  # percentage of each class of the category
        else:
            label = p.get_height()  # count of each level of the category

        x = p.get_x() + p.get_width() / 2  # width of the plot
        y = p.get_height()  # height of the plot

        ax.annotate(label,(x, y),ha="center",va="center",size=12,xytext=(0, 5),textcoords="offset points",)  # annotate the percentage

    plt.show()  # show the plot

# day_of_week

df = data.copy()

from pandas.api.types import CategoricalDtype
cats     = [ 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
cat_type = CategoricalDtype(categories=cats, ordered=True)

df['day_of_week']=df['day_of_week'].astype(cat_type)

labeled_barplot(df, 'day_of_week', 'sentiment')

"""- All weekdays (except Tuesdays) have majority of tweets as positive tweets, while weekends & Tuesdays have majority of tweets as neutral tweets"""

# hour

plt.figure(figsize=(9,5))
sns.histplot(data=data, x='hour');

"""- Majority of the tweets are in the late afternoons & evenings (peaking after 3PM)

New features will be created by counting number of positive & negative words in each tweet. The list of all positive & negative words are borrowed from this study: https://www.cs.uic.edu/~liub/FBS/sentiment-analysis.html
"""

positive_words = pd.read_csv('/content/drive/MyDrive/positive-words.txt', skiprows=35, names=['words'])
positive_words = positive_words['words'].values.tolist()

negative_words = pd.read_csv('/content/drive/MyDrive/negative-words.txt', skiprows=35, names=['words'])
negative_words = negative_words['words'].values.tolist()

# Let's create new features, i.e., number of positive & negative words associated with each text

# Defining a function to count number of positive & negative words

def count_words(tweet, words):
    count = 0
    for word in tweet.split(' '):
        if word in words:
            count += 1
    return count

data['number_positive_words'] = data['text'].apply(count_words, words=positive_words)
data['number_negative_words'] = data['text'].apply(count_words, words=negative_words)

# Function to create stacked barplots

def stacked_barplot(data, predictor, target):

    count = data[predictor].nunique()
    sorter = data[target].value_counts().index[-1]
    tab1 = pd.crosstab(data[predictor], data[target], margins=True).sort_values(by=sorter, ascending=False)
    print(tab1)
    print("-" * 120)
    tab = pd.crosstab(data[predictor], data[target], normalize="index").sort_values(by=predictor, ascending=True)
    tab.plot(kind="bar", stacked=True, figsize=(count + 5, 5))
    plt.legend(loc="lower left", frameon=False,)
    plt.legend(loc="upper left", bbox_to_anchor=(1, 1))
    plt.show()

# number_positive_words

stacked_barplot(data, 'number_positive_words', 'sentiment')

"""- Tweets with 0 or 1 count for number_positive_words have all three sentiments 'neutral', 'positive' & 'negative'
- Tweets with 1, 2, 3 or 4 number_positive_words are majorly a 'positive' sentiment as expected
"""

# number_negative_words

stacked_barplot(data, 'number_negative_words', 'sentiment')

"""- Tweets with 0 or 1 count for number_negative_words have all three sentiments 'neutral', 'positive' & 'negative'
- Tweets with 2, 3 or 4 number_negative_words are majorly a 'negative' sentiment as expected
"""

data.head()

# Convert tweets to lowercase

data['text'] = data['text'].str.lower()

# Remove non-alphanumeric character from tweets such as '@'

def remove_non_alphanumeric(tweet):
    pattern = re.compile('\W')
    x = re.sub(pattern, ' ', tweet)
    return(x)

data['text'] = data['text'].apply(remove_non_alphanumeric)

data.head()

"""- The text has been converted to lowercase & non-alphanumerical characters such as @ & # have been removed"""

# Tokenize sentences to arrays of words

data['tokens'] = data['text'].apply(nltk.word_tokenize)

data.head()

# Lemmatize the words

lem = WordNetLemmatizer()
data['tokens'] = data['tokens'].apply(lambda x: [lem.lemmatize(word) for word in x])

data.head()

"""- We can see examples of words being broken down to the root like markets has become market & ads has become ad"""

# Stemming the words

stem = PorterStemmer()
data['tokens'] = data['tokens'].apply(lambda x: [stem.stem(word) for word in x])

data['tokens'] = data['tokens'].str.join(' ')

data.head()

"""- We can see examples of words being broken down to root (irrespective of the tense) like please & pleased has become pleas"""

# Let's plot a word cloud to see the difference between original tweets & tweets post data cleaning

# Original tweets

data['text'].to_csv('tweetsonly.csv')
text2 = open('tweetsonly.csv').read()

wordcloud = WordCloud().generate(text2)
plt.imshow(wordcloud)
plt.axis("off")
plt.show()

# tweets post data cleaning

data['tokens'].to_csv('cleanedtweetsonly.csv')
text3 = open('cleanedtweetsonly.csv').read()

wordcloud = WordCloud().generate(text3)
plt.imshow(wordcloud)
plt.axis("off")
plt.show()

"""- 'cibc', 'co', 'bank', 'thank' are some of the common word occurrences in cleaned up tweets
- 'HTTPS' was a common occurrence in the original tweets but is no longer a common occurrence in cleaned up tweets
"""

# Dropping text column

data = data.drop('text', axis=1)

# Clean up locations column

data['location'].value_counts().head(25)

"""- This column is too unclean and will be dropped from analysis"""

data = data.drop('location', axis=1)

"""### Machine Learning"""

data['sentiment'] = data['sentiment'].replace({'neutral':0, 'positive':1, 'negative':-1})
data['sentiment'] = data['sentiment'].astype(int)

# Assign features & target as X & y respectively

X = data.drop('sentiment', axis=1)
y = data['sentiment']

# One hot encoding of day_of_week column

X = pd.get_dummies(X, columns=['day_of_week'], drop_first=True)

# Split data into train & test set using stratify to maintain the split of sentiment across train & test sets

X_train_full, X_test, y_train_full, y_test = train_test_split(X, y, test_size=0.20, random_state=1, stratify=y,\
                                                   shuffle=True)

# Shape of splits

X_train_full.shape

X_test.shape

"""- There are now 10 columns & 1560 and 391 rows respectively in full training & test sets"""

y_train_full.value_counts(normalize=True)

y_test.value_counts(normalize=True)

"""- Stratify has maintained the split of neutral ('0'), positive ('1') & negative ('-1') tweets in the dataset

### 5-fold cross validation scores (default model parameters)

We would like each class to be predicted correctly. Tuning the 'F1' metric will ensure the maximum possibility of correct predictions across each of the target classes

Further, the following additional points need consideration

- Vectorizer 'TFIDF' is chosen to convert text data to numerical feature matrix
- RandomOverSampler would be needed to handle class imbalance across target classes
- Further, choice of ML model(s) that work well with textual data- Multinomial Naive Baiyes, Linear Support Vector Classifier, Random Forest Classifier & XGBoost
"""

import time

# Initialize vectorizer TfidfVectorizer with default parameters, & stop_words as english

vectorizer  = TfidfVectorizer(stop_words='english')

# Initialize oversampler

oversampler = RandomOverSampler(random_state=1)

# Initialize ML models with default parameters

models      = [("SupportVectorMachine",  LinearSVC(random_state=1)),
              ("MultinomialNaiveBayes",  MultinomialNB()),
              ("RandomForest",           RandomForestClassifier(random_state=1)),
              ("XGBoost",                XGBClassifier(random_state=1, eval_metric='mlogloss'))]

results  = []
names    = []

print("Cross Validation Model Performance on Training Set - TfidfVectorizer\n")

# Loop through models & calculate mean cross validated scores
for name, model in models:

    scores   = []
    times    = []

    kf = StratifiedKFold(n_splits=5, random_state=1, shuffle=True)

    for train_index, val_index in kf.split(X_train_full, y_train_full):

        X_train, X_val = X_train_full.iloc[train_index], X_train_full.iloc[val_index]
        y_train, y_val = y_train_full.iloc[train_index], y_train_full.iloc[val_index]

        # vectorization

        num_tweets_train = vectorizer.fit_transform(X_train['tokens'])
        num_tweets_val   = vectorizer.transform(X_val['tokens'])

        feature_names= vectorizer.get_feature_names_out()

        bow_df_train = pd.DataFrame(num_tweets_train.toarray(), columns=feature_names)
        bow_df_val   = pd.DataFrame(num_tweets_val.toarray(),   columns=feature_names)

        X_train   = X_train.drop('tokens', axis=1)
        X_val     = X_val.drop('tokens', axis=1)

        X_train_f = X_train.reset_index(drop=True).merge(bow_df_train.reset_index(drop=True), left_index=True, right_index=True)
        X_val_f   = X_val.reset_index(drop=True).merge(bow_df_train.reset_index(drop=True), left_index=True, right_index=True)


        # oversampling

        X_train_f_over, y_train_over = oversampler.fit_resample(X_train_f, y_train)

        # model fit & prediction

        start = time.time()
        model.fit(X_train_f_over, y_train_over)

        y_pred = model.predict(X_val_f)
        end = time.time()

        score = f1_score(y_val,y_pred, average='macro') # get avg f1_score across classes
        time_ = end - start

        scores.append(score)
        times.append(time_)

    names.append(name)
    results.append(sum(scores)/len(scores))

    print(f'{name} : {sum(scores)/len(scores)}')
    print(f'Time : {sum(times)/len(times)}')
    print('\n')

"""- Best scores were with Multinomial Naive Bayes & XGBoost. Multinomial Naive Bayes takes the least amount of time to fit & predict, while XGBoost takes the maximum amount of time
- Random Forest is easier to interpret with class_feature_importance built in the module with not much compromise in performance score & time

The next step will involve tuning hyperparameters for the vectorizer & the chosen model in an effort to improve performance further

### Hyperparameter Tuning - GridSearchCV - RandomForest
"""

pipe       = Pipeline(
                    [('TfidfVectorizer',TfidfVectorizer(stop_words='english')),
                     ('oversampler',    RandomOverSampler(random_state=1)),
                     ('RandomForest',   RandomForestClassifier(random_state=1))])

parameters = {
              'TfidfVectorizer__ngram_range' : [(1,1),(1,2)],
              'TfidfVectorizer__max_features': range(1000,10000,2500),
              'RandomForest__n_estimators'   : range(10,100,25),
              'RandomForest__criterion'      : ['gini', 'entropy'],
              'RandomForest__max_depth'      : range(3,15,3),
              'RandomForest__max_features'   : ['auto', 'sqrt'],
            }

def GridSearchCV_(estimator, estimator_params, X, y):

    kf = StratifiedKFold(n_splits=3, random_state=1, shuffle=True)

    best_score   = 0
    best_params  = None

    for params_permut in ParameterGrid(estimator_params):

        scores   = np.empty(kf.n_splits)

        estimator.set_params(**params_permut)

        for i, (train_index, val_index) in enumerate(kf.split(X_train_full, y_train_full)):

            X_train, X_val = X_train_full.iloc[train_index], X_train_full.iloc[val_index]
            y_train, y_val = y_train_full.iloc[train_index], y_train_full.iloc[val_index]

            # vectorization

            num_tweets_train = estimator.steps[0][1].fit_transform(X_train['tokens'])
            num_tweets_val   = estimator.steps[0][1].transform(X_val['tokens'])

            feature_names= estimator.steps[0][1].get_feature_names_out()

            bow_df_train = pd.DataFrame(num_tweets_train.toarray(), columns=feature_names)
            bow_df_val   = pd.DataFrame(num_tweets_val.toarray(),   columns=feature_names)

            X_train   = X_train.drop('tokens', axis=1)
            X_val     = X_val.drop('tokens', axis=1)

            X_train_f = X_train.reset_index(drop=True).merge(bow_df_train.reset_index(drop=True), left_index=True, right_index=True)
            X_val_f   = X_val.reset_index(drop=True).merge(bow_df_val.reset_index(drop=True), left_index=True, right_index=True)

            # oversampling

            X_train_f_over, y_train_over = estimator.steps[1][1].fit_resample(X_train_f, y_train)

            # fit & prediction

            estimator.steps[2][1].fit(X_train_f_over, y_train_over)

            y_pred = estimator.steps[2][1].predict(X_val_f)

            scores[i] = f1_score(y_val,y_pred, average='macro') # get avg weighted f1_score across classes

        scores_mean   = scores.mean()

        if scores_mean>best_score:
            best_params= params_permut
            best_score = scores_mean


    print(f'Best Hyperparameters are:\n {best_params}')
    print(f'Best Score is:\n {best_score}')

GridSearchCV_(pipe, parameters, X_train_full, y_train_full)

"""#### Building the final classifier & making predictions using the test set"""

# The steps can be built into a function

def sentiment(X_sample, X, y):   # X & y are the features & predictions for known dataset
                                 # & X_sample is feature set for data where sentiment(s) are unknown

    pipe_final   = Pipeline(
                [('TfidfVectorizer',TfidfVectorizer(stop_words='english', ngram_range=(1, 1),max_features=1000)),
                 ('oversampler',    RandomOverSampler(random_state=1)),
                 ('RandomForest'   , RandomForestClassifier(random_state=1, criterion='gini',\
                                                             max_depth=12, max_features='auto', \
                                                             n_estimators=85))])

    # vectorization

    num_tweets            = pipe_final.steps[0][1].fit_transform(X['tokens'])
    num_tweets_sample     = pipe_final.steps[0][1].transform(X_sample['tokens'])

    feature_names         = pipe_final.steps[0][1].get_feature_names_out()

    bow_df_full           = pd.DataFrame(num_tweets.toarray(), columns=feature_names)
    bow_df_sample         = pd.DataFrame(num_tweets_sample.toarray(), columns=feature_names)

    X                     = X.drop('tokens', axis=1)
    X_sample              = X_sample.drop('tokens', axis=1)

    feature_names_in_     = list(X.columns)

    X_f                   = X.reset_index(drop=True).merge(bow_df_full.reset_index(drop=True), left_index=True, right_index=True)
    X_sample_f            = X_sample.reset_index(drop=True).merge(bow_df_sample.reset_index(drop=True), left_index=True, right_index=True)

    # oversampling

    X_f_over, y_over      = pipe_final.steps[1][1].fit_resample(X_f, y)

    # model fit & prediction

    pipe_final.steps[2][1].fit(X_f_over, y_over)

    pred                  = pipe_final.steps[2][1].predict(X_sample_f)

    feature_names         = feature_names_in_ + list(pipe_final.steps[0][1].get_feature_names_out())

    return pred, pipe_final.steps[2][1], feature_names, X_f_over, y_over

# Testing

pred_test, tuned_model, feature_names, X_, y_  = sentiment(X_test, X_train_full, y_train_full)

print('Final Classifier Unbiased Testing Performance:')
print(classification_report(y_test, pred_test))

"""- The final classifier is able to achieve a F1 score of ~65% for negative sentiments, ~>=75% for positive & neutral sentiments

### Feature Importance
"""

from sklearn.preprocessing import scale
from collections import OrderedDict
def class_feature_importance(X, y, class_labels, feature_names, feature_importances, max_top = 20):
    """
    Saves feature importances by class
    Reworked version of https://stackoverflow.com/a/36201964

    Arguments:
    X, y - array of features and labels
    class_labels - labels corresponding to values in y. For example, if y has [0, 1, 2], class_labels can be ['neg', 'pos', 'neutral']
    feature_names - names of columns in X
    feature_importances - obtained from a classifier such as decision tree
    max_top - the maximum number of most important features for each class to keep

    Returns:
    result - dictionary of feature importances by class
    """
    X = scale(X)

    result = {}
    # extract feature importances by class
    for c in set(y):
        result[class_labels[c]] = dict(zip(feature_names, np.mean(X[y == c, :], axis = 0) * feature_importances))

    # sort by importance and keep the most important
    for cname in result.keys():
        result[cname] = sorted(result[cname].items(), key = lambda x: x[1], reverse = True)[:max_top]

    return result

class_feature_importance(X_, y_, [0,1,-1], \
                         feature_names, tuned_model.feature_importances_)

"""### Summary & Conclusion

- TextBlob was used to assign sentiment labels to tweets. There was inherently some imbalance in classes of sentiments for the dataset; negative:neutral:positive ratio was 0.15:0.43:0.40


- Data cleaning, visualization was followed by text analytics (removing non alphanumeric characters, tokenizing sentences, lemmatization, removing stop words & performing vectorization using TF-IDF). This was followed by randomoversampling to handle target imbalance


- Four different base models were fitted to the training set. The best cross validated scores though were achieved with MultinomialNB & XGBoost; however Random Forest was chosen for hyperparameter tuning as it's easier to interpret with the class feature improtances, & with not much compromise with score & computational time


- A pipeline was further built for TF-IDF & Random Forest, thereby enabling tuning for the best hyper-parameters. Post tuning, performance was enhanced to achieve a F1 score of ~0.65 for negative sentiment & >0.75 for neutral & positive sentiments on unseen test data


- For the final model, feature importance was identified for all 3 classes (negative, neutral & positive tweets). As expected
  - number_negative_words had high feature importance for predicting negative sentiments & number_positive_words had high feature importance for predicting positive sentiments
  - The words of importances associated with negative tweets were found to be 'flat', 'mortgage', 'single', 'low', 'sorry', 'close' etc
  - The words of importances associated with positive tweets were found to be 'new', 'thank', 'wood', 'latest', 'game', 'love', 'home', 'great', 'good'
  - The words of importances associated with neutral tweets were found to be 'http', 'cibc', 'company', 'recruit', 'reaffirm', 'provide'

 The feature importance words & tweet sentiments make somewhat intuitive sense lending confidence in the explainability of the final model!
"""